[terminal.shell]
program = "/opt/homebrew/bin/zellij"
args = ["attach", "-c", "main"]

# program = "/opt/homebrew/bin/fish"
# args = ["--login", "-c", "/opt/homebrew/bin/tmux new-session -A -s main"]

[window]
dynamic_title = false
dimensions = { columns = 88, lines = 28 }
padding = { x = 10, y = 10 }
decorations = "full"

[font]
size = 15
normal.family = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
