import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[window]
dynamic_title = false
dimensions = { columns = 88, lines = 28 }
padding = { x = 10, y = 10 }

[font]
size = 15.0
normal.family = "FiraCode Nerd Font"
