#!/bin/sh

# shorten long commands
alias \
    kc="kubectl" \
    gk="gitkraken" \
    lg="lazygit" \
    yy="yazi"

# new commands
alias \
    vim="nvim" \
    jq="yq" \
    shred="rm -P" \
    view="nvim -R" \
    tree="eza --tree" \
    help="aichat -r shell:zsh"

# overwrite commands
alias \
    exa="eza"

# Colorize commands when possible.
alias \
    ls="ls -G" \
    less="less -R" \
    grep="grep --color=auto" \
    diff="diff --color=auto"
