#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Colorize commands when possible.
alias \
		ls="ls -G"

alias \
	addmark="mark" 

# hack for sudoedit
alias \
	sudoedit="sudo -e"

# shorten git commands
alias \
	gi="git init" \
	ga="git add" \
	gaa="git add ." \
	gc="git commit" \
	gcm="git commit -m" \
	gp="git push" \
	gs="git status" \
	gd="git diff" \
	gdh="git diff HEAD" \
	gl="git log" \
	glg="git log --graph" \
	glp="git log -p" \

# shorten long commands
alias \
	fs="fsession" \
	"tmux-attach"="tmux -f ~/.config/tmux/tmux.conf new-session -A -s main" \
	ta="tmux-attach" \

# new commands
alias \
	pycalc="python -i -c 'from math import *'" \
	shred="rm -P" \
	view="nvim -R"

