#:schema https://starship.rs/config-schema.json

add_newline = true

[character]
success_symbol = "🦄"
error_symbol = "🚨"
vimcmd_replace_one_symbol = "🦄"
vimcmd_replace_symbol = "🦄"
vimcmd_symbol = "🦄"
vimcmd_visual_symbol = "🦄"

[direnv]
symbol = "🌍 "
style = "bold green"
format = 'with [${symbol}${allowed}${loaded}]($style) '
disabled = false
allowed_msg = ""
denied_msg = "**"
not_allowed_msg = "*"
unloaded_msg = "unloaded"
detect_files = [".envrc", ".env"]
