#:schema https://starship.rs/config-schema.json

add_newline = true

[character]
success_symbol = "🦄"
error_symbol = "🚨"
vimcmd_replace_one_symbol = "🐴"
vimcmd_replace_symbol = "🐴"
vimcmd_symbol = "🦄"
vimcmd_visual_symbol = "🐴"
