# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

# Default keymaps are at https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
    # Goto
    { on = ["g", "k"], run = "cd ~/Desktop", desc = "Go to desktop" },
    { on = ["g", "o"], run = "cd ~/Documents", desc = "Go to documents" },

    # Copy
    { on = ["c", "t"], desc = "Copy contents of file", run = ''' shell 'cat "$0" | pbcopy' --confirm''' },
]
