[runtime]
output_max_bytes = 8000000
reactive_tests = true
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
auto_reload = "off"
auto_instantiate = true
watcher_on_save = "lazy"

[language_servers.pylsp]
enable_ruff = true
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enabled = true
enable_mypy = true
enable_pyflakes = false

[package_management]
manager = "pip"

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[completion]
copilot = false
activate_on_typing = true

[keymap]
preset = "vim"

[keymap.overrides]

[ai]
rules = ""

[snippets]
custom_paths = []
include_default_snippets = true

[experimental]

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[display]
default_width = "medium"
code_editor_font_size = 14
default_table_page_size = 10
cell_output = "above"
theme = "light"
dataframes = "rich"

[diagnostics]
