set -g prefix C-a
unbind C-b

# vi mode
set -g status-keys vi
setw -g mode-keys vi

# smart pane switching with awareness of vim splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# Enable Powerline symbols (unless already specified otherwise in environment)
if-shell ': ${TMUX_POWERLINE_SYMBOLS?}' '' 'set-environment -g TMUX_POWERLINE_SYMBOLS "powerline"'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Options

set-option -g status-justify centre
set-option -g status-style fg=white,bg=black
set-option -g status-left "[#S]"
set-option -g status-left-length 30
set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-window-option -g window-status-current-style bg=yellow,fg=black
